title: "PostgreSQL チュートリアル"
summary: "PostgreSQLの基本操作を学べるチュートリアルです"
topics: ["SQL","PostgreSQL"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - install
  - createdb
  - createtable
  - select
  - insert
  - where
